name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Setup key
#      - run: set -eu
#      - name: Install SSH Key
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#      - name: Deploy with rsync
#        run: rsync -avz ./dist/ $root@$134.209.225.137:/var/www/vlazaay
      - run: cd /var/www/vlazaay
      - run: git pull

